import string

from django.core.validators import RegexValidator

USERNAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 254
CONFIRMATION_CODE_MAX_LENGTH = 255
CONFIRMATION_CODE_LENGTH = 6
CONFIRMATION_CODE_ALPHABET = string.digits
PROFILE_URL_PATH = 'me'
RESERVED_USERNAMES = (PROFILE_URL_PATH,)
MIN_SCORE = 1
MAX_SCORE = 10
TEXT_PREVIEW_LENGTH = 50
SLUG_MAX_LENGTH = 50
NAME_MAX_LENGTH = 256

USERNAME_PATTERN = r'^[\w.@+-]+\Z'
VALIDATE_USERNAME_PATTERN = RegexValidator(regex=USERNAME_PATTERN)
